import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f5ff',
          100: '#dbe6fe',
          500: '#3d5afe',
          600: '#3247d1',
          700: '#28389f',
        },
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#31312b",
        "surface-container-highest": "#e5e2da",
        "tertiary-fixed": "#ffdbcc",
        "secondary-fixed": "#e7e1de",
        "primary-fixed": "#d8e7cf",
        "surface-dim": "#dddad1",
        "tertiary": "#763d20",
        "on-surface-variant": "#444841",
        "inverse-primary": "#bccbb4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb694",
        "secondary-container": "#e4dfdb",
        "on-error-container": "#93000a",
        "on-background": "#1c1c17",
        "on-primary-fixed": "#121f10",
        "secondary": "#615e5b",
        "on-surface": "#1c1c17",
        "surface-container": "#f1eee5",
        "on-secondary-container": "#65625f",
        "on-primary-container": "#d7e6ce",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffdacb",
        "surface-container-low": "#f6f3ea",
        "surface-tint": "#546250",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#6f371b",
        "primary": "#42503e",
        "tertiary-container": "#935435",
        "on-secondary-fixed": "#1d1b19",
        "inverse-on-surface": "#f4f1e8",
        "primary-container": "#5a6855",
        "on-tertiary-fixed": "#351000",
        "surface": "#fcf9f0",
        "surface-container-high": "#ebe8df",
        "background": "#fcf9f0",
        "outline-variant": "#c4c8bf",
        "surface-bright": "#fcf9f0",
        "on-secondary-fixed-variant": "#494644",
        "secondary-fixed-dim": "#cbc5c2",
        "outline": "#747871",
        "on-primary-fixed-variant": "#3d4a39",
        "primary-fixed-dim": "#bccbb4",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2da",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-sm": "0.75rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "container-max": "1360px",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "caption": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "title-md": ["Manrope", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "caption": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "400" }],
        "display-lg-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "title-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
